---

# -----------------------------------------------------------------------------
# public ansible galaxy
# -----------------------------------------------------------------------------

- src: cloudalchemy.alertmanager
  version: 0.19.1

- src: cloudalchemy.grafana
  version: 0.18.0

- src: cloudalchemy.node_exporter
  version: 1.0.0

- src: cloudalchemy.prometheus
  version: 3.0.0

- src: cloudalchemy.snmp-exporter
  version: 1.0.0

- src: geerlingguy.docker
  version: 2.1.0

...
