---
grafana_package: "www-apps/grafana-bin{{ (grafana_version != 'latest') | ternary('-' ~ grafana_version, '') }}"
# https://unix.stackexchange.com/questions/534463/cant-enable-grafana-on-boot-in-fedora-because-systemd-sysv-install-missing
grafana_dependencies: []
grafana_server_service_name: "grafana"
